services:
  frontend:
    image: my-vue-app-banco-familar
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      VITE_APP_API_BASE_URL: http://backend:4300
    depends_on:
      - backend

  backend:
    image: my-nestjs-backend-banco-familar
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4300:4300"
    environment:
      NODE_ENV: production
      JWT_SECRET: your_jwt_secret
      JWT_EXPIRATION_TIME: 60m
      DATABASE_URL: mysql://root:admin@148.113.196.135:3307/banco_familiar

volumes:
  db_data: